### ISSUE TITLE
Empty line is added after a wrapped up line

### ISSUE THREAD

**Issue by mykhailo-gaidai** [gmlewis/go-flutter-stylizer#13] opened 2022-11-20 07:11 UTC
It looks like if the line crosses the max line length and is being wrapped, stylizer adds an empty line below it (there are 2 extra lines in the screenshot code - above `_getPrescription` and above `_getUserAddress`).
<img width="789" alt="image" src="https://user-images.githubusercontent.com/9654565/202889674-0652c459-a849-4c91-b81a-0f5f801e7a9b.png">

Increasing line length up to the value that prevents wrapping removes the lines
<img width="892" alt="image" src="https://user-images.githubusercontent.com/9654565/202890094-d2170c52-44a3-4aad-ad16-5f2f7a53cd22.png">

**Comment by gmlewis** [comment] 2022-11-20 13:15
Thanks for the report. This is indeed how it was designed. Single-liners can be grouped tightly together with no breaks in between, but multi-line statements are separated for clarity.

Closing as working-as-intended.

**Closed as completed by gmlewis** 2022-11-20 13:15 UTC
